Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -9,6 +9,15 @@ jobs:
   deploy:
     runs-on: ubuntu-latest
     steps:
+      - name: VALIDACIÓN DE SECRETS (Temporal)
+        run: |
+          echo "Host (parcialmente, censurado por seguridad): ${{ secrets.SSH_HOST }}"
+          echo "Usuario (visible): ${{ secrets.SSH_USERNAME }}"
+          if [ -z "${{ secrets.SSH_HOST }}" ] || [ -z "${{ secrets.SSH_USERNAME }}" ]; then
+            echo "¡ERROR CRÍTICO! Uno o más secrets (HOST/USERNAME) están vacíos."
+            exit 1
+          fi
+          echo "Validación de Secrets: OK. Los valores base están presentes."
       - name: Ejecutar comandos remotos
         uses: appleboy/ssh-action@v1.2.2
         with:
